###############################
#   suizld's hypraper config  #
###############################

preload = /home/suizld/Imagens/Wallpapers/wallpapersden.com_post-apocalyptic-s-t-a-l-k-e-r_2560x1080.jpg
wallpaper = , /home/suizld/Imagens/Wallpapers/wallpapersden.com_post-apocalyptic-s-t-a-l-k-e-r_2560x1080.jpg
