###
# suizld's hyprsunset config
###

max-gamma = 100

################
#   profiles   #
################

profile {
    time = 7:30 # disable at 7:30 (7:30 am)
    identity = true
}

profile {
    time = 21:00 # enable at 21:00 (9:00 pm)
    temperature = 5000
}
