###############################
#   suizld's hypraper config  #
###############################

preload = /home/suizld/Imagens/Wallpapers/wallpaperflare.com_wallpaper.jpg
wallpaper = , /home/suizld/Imagens/Wallpapers/wallpaperflare.com_wallpaper.jpg
