###############################
#   suizld's hypraper config  #
###############################

preload = /home/suizld/Imagens/Wallpapers/vivo-x-fold-modern-3840x2160-23595.jpg
wallpaper = , /home/suizld/Imagens/Wallpapers/vivo-x-fold-modern-3840x2160-23595.jpg
